name: POC Scanner Giornaliero

on:
  schedule:
    # L'orario è espresso in formato CRON ed è basato sul fuso orario UTC.
    # In Italia le 06:00 corrispondono alle 04:00 UTC (durante l'ora legale) o alle 05:00 UTC (durante l'ora solare).
    # Questa configurazione è impostata sulle 04:00 UTC.
    - cron: '0 4 * * *'
  
  # Questo ti permette di testare ed avviare lo scanner manualmente cliccando un bottone su GitHub
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
    # 1. Scarica il codice del tuo repository sulla macchina virtuale di GitHub
    - name: Checkout del codice
      uses: actions/checkout@v4

    # 2. Configura l'ambiente Python
    - name: Configura Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # Ottimizza i tempi di avvio memorizzando le librerie

    # 3. Installa le librerie necessarie (pandas, yfinance, ecc.)
    - name: Installa le dipendenze
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Esegue lo script Python che invia i messaggi a Telegram
    - name: Esegui POC Scanner
      run: python cron_scanner.py
